### PR TITLE
scap-security-guide expects b32 audits for all arches

### PR DESCRIPTION
**Pull request by jamescassell**

### CODE REVIEW

**Comment by jamescassell** [comment]
SSG is arguably correct here (and the STIG wrong,) otherwise I'd open a bug against the ssg project. scap-security-guide is theoretically "upstream" for the DISA STIG.

**Comment by LeamHall** [comment]
Can't agree with tyou on this. The STIG is what organizations get evaluated on. They have been wrong for years and show no sign of stopping. The SSG is an educated opinion, not a standard of measurement. Note that I'm not saying the SSG is wrong, but the STIG is "right" in that it is the standard being evaluated against. Well, I am saying the SSG isn't really useful unless you have a lot more RHCE's that average organizations.

**Comment by shepdelacreme** [comment]
This is a minor change that brings it inline with some of the changes in the RHEL7 STIG role. Allowing for the SSG benchmark work around doesn't alter the normal operation of the role or meeting STIG compliance.

However I have to agree with @LeamHall here. I've never been a party to DISA using the SSG when they come audit people. They use the letter of the STIG.

**Comment by shepdelacreme** [comment]
@jamescassell Yeah I'm fine leaving this default to true. Gonna leave this one open to comments for a bit and then I'll merge.

**Comment by LeamHall** [comment]
My "Ansible brain" is still pretty much a newbie. How hard would it be to have an "ssg" tag that performed SSG specific actions? The issue with including SSG material in a STIG environment is that the averate "STIG Environment" does not have a bunch of  RHCE level people with free time to reconfigure stuff. However, some shops do have the people, need, and desire to go the extra mile for higher level security. Is it possible to meet both needs?

**Pull request merged**
