### PR TITLE
Remove audit tasks, update to V1R15, and refactor cat 1 and 2 checks

### LINKED ISSUE #105: Deprecation Warning: always_run
Receiving a Deprecation Warning that always_run will be removed in Ansible 2.4. Fix is to change "always_run: yes" to "check_mode: no" in (RHEL6-STIG-0.9.3/tasks/ ):

- prelim.yml
- cat1.yml
- cat2.yml
- cat3.yml
- not_automated.yml

### PR DESCRIPTION
**Pull request by shepdelacreme**
Fixes #105 #97 #103 #94 #48 #23

### CODE REVIEW

**Comment by shepdelacreme** [comment]
This is a major change to the role, would appreciate any feedback.

**Comment by LeamHall** [comment]
If this weekend is soon enough for testing, I'll run some vanilla CentOS 6 kvms through it.

**Comment by shepdelacreme** [comment]
@LeamHall That works..thank you!

**Comment by LeamHall** [comment]
@shepdelacreme Initial functional tests work, now that I almost know what I'm doing.  :)

We've had storms here so I haven't been able to get as much done as I wanted. I starting writing a [failure playbook](https://github.com/LeamHall/Ansible_Test/blob/master/playbooks/violate_stigs.yml) starting with [telnet](https://github.com/LeamHall/Ansible_Test/blob/master/playbooks/tasks/bad_telnet.yml). Wasn't sure if you already have something like that or if continuing would be a worthwhile endeavor. Thoughts?

I also had some old Ruby code to much STIGs into picked JSON fields. Probably need to redo in Python so we can build a better data source. Do you have anything like that already?

**Comment by shepdelacreme** [comment]
@leamhall Thanks! 

For the failure playbook, is this essentially a playbook that would cause each of the STIG checks to fail? If so this is something I've toyed with for testing purposes for a while but never got around to starting. I think it would be great to validate the tasks with! 

For the tiny code I'm not clear what your intent is with it. Did you use it to perform STIG audits and put pass/fail into JSON? I'm intrigued regardless.

I'm going to leave this PR open a bit longer for more testing/comments.

**Comment by LeamHall** [comment]
@shepdelacreme yes, the playbook is to create failures to test that they are detected and fixed. I tend to mentally group STIG items by category, not VID. So all the services stuff or audit stuff would be together. The issue is that multiple VIDs have the same fix action and it seems easier to group things so a person can focus on one topic and then move on to the next. Feedback welcome!

Also, have you run ansible-lint on the new code?

The STIGs are getting more of the CCI identifiers into the VID relationships. Some IA shop documentation requirements only look at CCIs and there's no good way to correlate CCI to STIG VID, at least when I was working on it a couple years ago. In that the STIGs are mangled XML (like having '&lt' instead of '<') pulling it into a cleansed format seemed best. JSON was portable and goes into MongoDB well.  :)  Haven't gotten that far though.

Also, being able to parse and store means we can compare from version to version and quickly identify what changed in the new versions. I'm loathe to trust my team's success on the change list editor getting everything.

**Comment by samdoran** [comment]
Rather thar writing failure playbooks, a better approach would be to run an OpenSCAP test and see if it pass/fails. That's what the original CI tests did, but they exist in the Ansible Lockdown project and not in this repo.

I've been meaning for some time to move those tests into the role directly, but have not made the time to do so. I'm out of the country this week. Maybe I'll be able to move that over next week. I also switched jobs, so hopefully I will have more time to work on this project.

Very glad you're making some good headway on these changes. Thanks!

**Comment by LeamHall** [comment]
Hey @samdoran ! I appreciate all the work you did on this stuff! I'm learning Ansible and learning to do it right by doing a lot of reading.  :)

Last time I looked at OpenSCAP it was a bad fit for a shop needing STIG compliance. The Failure Playbooks need to be tunable to a site's needs. Still working on that bit.

Good news on the job shift and travel. Whether for business or pleasure travel is usually fun!

**Pull request merged**
